### ISSUE TITLE
Web links are rendered as regular text.

### ISSUE THREAD

**Issue by andreas-vester** [mkdocstrings/griffe#106]
**Describe the bug**
Web links within the docstring are rendered as regular text rather than a web link.

**To Reproduce**
```
def docstest(int_val: int) -> int:
    """Function to showcase docstring problems.

    This docstring demnonstrates some issues using ``mkdocstrings`` with respect to hyperlinks. They will get rendered as regular text.

    Parameters
    ----------
    int_val
        Integer value. Please see https://en.wikipedia.org/wiki/Integer.

    Returns
    -------
    int
        Returns an integer value.

    """
    pass
```

**Expected behavior**
https://en.wikipedia.org/wiki/Integer should get rendered as a web link.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29901736/196045148-f06b3e88-9403-4b6c-992f-5e00834f7771.png)

**System (please complete the following information):**
- `griffe` version: 0.22.2
- Python version: 3.10

**Comment by pawamoy** [comment]
Try adding `pymdownx.magiclink` to your Markdown extensions in `mkdocs.yml`:

```yaml
markdown_extensions:
- pymdownx.magiclink
```

**Comment by pawamoy** [comment]
Please ask for reopening if the above suggestion does not solve your issue.
