### ISSUE TITLE
Incorrect type reference in code.

### ISSUE THREAD

**Issue by Tonivalle** [mkdocstrings/griffe#111]
On the `inspector.py` file, `inspect_staticmethod` references `classmethod` in the last line of the function and `inspect_classmethod` references `staticmethod`, which should be reversed since every other function references the correct type when calling `handle_function`.

See snippet for the lines of code:
https://github.com/mkdocstrings/griffe/blob/90bded46ccaab0417ed57ed11d3b67597f3845ba/src/griffe/agents/inspector.py#L280-L294

**Comment by pawamoy** [comment]
Ha, nice catch! Will push a fix, thanks :slightly_smiling_face:
