### ISSUE TITLE
[BUG] `tuple[int, int] | None` causes IndexError, but `Optional[tuple[int, int]]` does not

### ISSUE THREAD

**Issue by bczsalba** [mkdocstrings/griffe#117]
**Describe the bug**
When trying to run `mkdocs serve` on [PyTermGUI](https://github.com/bczsalba/pytermgui/tree/new-docs), `pytermgui/ansi_interface` fails to be parsed due to an `IndexError`.

**To Reproduce**
1. Clone PyTermGUI and checkout `new-docs`
2. Run `mkdocs serve` in the git root
3. See error

**Expected behavior**
Things should be parsed.

**Screenshots**
> Everything above this was Jinja template stuff, so probably not very relevant.

<img width="1151" alt="Screenshot 2022-08-12 at 1 04 20" src="https://user-images.githubusercontent.com/66030897/184256746-7a3143e4-33cf-43c5-8989-022ec4308025.png">

**System (please complete the following information):**
- `pytkdocs` version: Not installed when the error first occured, still happens after installing 0.16.1.
- Python version: 3.9
- OS: MacOS

**Additional context**
I initially wanted to submit this issue over at griffe, but it turned out that it could parse the module no problem. Then I looked at `mkdocstrings`, and was redirected over to here. Note that `pytkdocs` wasn't installed by PIP when this started happening, and installing it didn't do much in terms of fixing the problem.

After messing around with the griffe source for a bit, I managed to narrow it down to this return annotation:

https://github.com/bczsalba/pytermgui/blob/06f2ec78d1b31d2a059035e72e8d1b014c929b81/pytermgui/ansi_interface.py#L156

After changing it to `Optional[tuple[int, int]]`, the error goes away.

No idea if I'm in the right place or not, or if the issue is completely up to me 🙂. I did look around for similar issues, but the one related post I found (#140) wasn't really what I was experiencing.

**Comment by pawamoy** [comment]
Fixed in 727456d, will try to release soon.
