### ISSUE TITLE
Properly documenting the return type in the "Returns" section when using google docstring style

### ISSUE THREAD

**Issue by tazend** [mkdocstrings/griffe#137]
Hi,

I noticed that when using the `google` parser for docstrings, it is not possible to properly document the return type of the return value within the `Returns` section itself without using type annotations or giving the value an explicit name.

**Example**

Consider the following test function, and generate the documentation for it with the `google` parser:

```
def test_func():
    """Return an integer.

    Returns:
        int: The integer
    """
    print("Hello friends!")
```

This results in the following:

![image](https://user-images.githubusercontent.com/75485188/225403788-0f41b2a8-3b32-4219-8041-d3fd0e7b6e6c.png)

Additionally, the following warning is generated:

`No type or annotation for returned value 'int'`

I would however expect the following to be generated:

![image](https://user-images.githubusercontent.com/75485188/225404547-e500bc6d-5a48-48bd-9a7d-6c0035e4a739.png)

The workaround to generate the correct layout like in the above screenshot is of course using type annotations, and rewriting it like this:

```
def test_func() -> int:
    """Return an integer.

    Returns:
        The integer
    """
    print("Hello friends!")
```

However, I think it would still be useful having the ability to simply specify the return type in the "Returns" section and getting the same layout as when using type annotations (and not giving the return value a name).

The primary reason I'm asking is because I'm working on a Cython project, and the github source-code viewer is absolutely not a friend of mixing Cython code with type annotations, and [displays this mess](https://github.com/PySlurm/pyslurm/blob/main/pyslurm/pyslurm.pyx#L328). Well, thats more of a github problem, but I'd still appreciate if it would be possible to have the correct layout generated without the use of type annotations :)

**Comment by tazend** [comment]
Hi,

thanks, that works good for now with the paranthesis 😄

**Comment by pawamoy** [comment]
@sanzoghenzo how should this get rendered? Do you expect a Returns section with just the type, and an empty description?

**Comment by sanzoghenzo** [comment]
Thanks for taking the time to review this!

I don't have a strong opinion for this; maybe just add it after the `property` literal, ath the same lone of the property name?
Or simply as a `Type: <type>` before the description?

I'm not much into style (as long as it's not ugly!), what matters to me is that the info is accessible and readable 😉

**Comment by pawamoy** [comment]
OK, then I'll reuse what is available, i.e. a dynamically added Returns section at the end of the docstring :slightly_smiling_face: Not the prettiest but you'll have the info rendered!
