### ISSUE TITLE
Inherited menber 

### ISSUE THREAD

**Issue by samsja** [mkdocstrings/griffe#138]
# Context

Hey, first thanks for the great tools!

I commented recently on this [issue](https://github.com/mkdocstrings/pytkdocs/issues/58) in pytkdocs.

My end goal is to make work the `inherited_members` of mkdocstring work.

I was about to create a PR for pytkdocs but I saw that the new python handler of mkdostring is using griffe. 

So I was wondering :

* is ìnherited_menbers` or something similar is implemented on griffe ?
* If no, I will try to draft a PR to fix it (as I really need to be able to show inherited method for my project), where should I start ?

Thanks in advance

**Comment by pawamoy** [comment]
Hello! Thanks for your help!

Erm, I had started working on it but can't find my local branch anymore... probably on another computer. Will let you know :slightly_smiling_face:

**Comment by samsja** [comment]
Great then !

**Comment by pawamoy** [comment]
So, I never found the branch I was talking about, hahaha... :skull: 
It only one or two functions, so it's fine, I'll just start again. Let me gather my thoughts again, and I'll report back, so that you can help, if needed and if you're still willing to :slightly_smiling_face:

**Comment by samsja** [comment]
I would be happy to do this PR. I found a hack on my side which is why I did not spend much time on this for now

**Comment by pawamoy** [comment]
Quick question: how would you then render inherited members in your docs?

Like this?

```md
::: path.to.my.Class
    options:
      inherited_members: true
```

Or would you like to reference specific inherited members, like this?

```md
::: path.to.my.Class.inherited_method
```

**Comment by samsja** [comment]
sorry I did not had time to answer. The first one seems more natural to me. But both looks fine honestly

**Comment by pawamoy** [comment]
Thanks! Yeah I've made it work in both cases anyway :slightly_smiling_face: 
It was pretty much guaranteed that users would want to access inherited members this way (second snippet).
It was a bit hard to pull off, but I managed to do that in a clean way :slightly_smiling_face:
