### ISSUE TITLE
Support for labels when decorating with custom decorators

### ISSUE THREAD

**Issue by a-recknagel** [mkdocstrings/griffe#141]
When decorating with [a few selected decorators](https://github.com/mkdocstrings/griffe/blob/7129477184f0b88d3bf165dfe8e1f6158c30914a/src/griffe/agents/visitor.py#L54-L68), the decorated function will get a label:

<img width="246" alt="Screenshot 2023-03-30 181803" src="https://user-images.githubusercontent.com/2063412/228900886-a097198d-e0c2-4bb0-a7eb-74c0d47d205e.png">

It would be nice if there were a way to

- be able to plug your own decorators into that list, maybe by implementing a protocol? (I'm not good with asts 😔)
- add 2nd and 3rd party decorators to that list as well (maybe even `functools.singeldispatch` and the dynamic `register`s that follow it)

**Comment by NowanIlfideme** [comment]
How would someone pass this to `griffe` when using `mkdocstrings`? If there is some sort of plugin mechanism (I see `exensions` but don't quite get how it works) that are loaded, we could just add our own definitions by mutating those global variables...

**Comment by pawamoy** [comment]
We have a new, shiny extension system, documented here: https://mkdocstrings.github.io/griffe/extensions/. Let me know if the docs are unclear!

**Comment by pawamoy** [comment]
Closing, the docs label on this issue will be enough when I add examples to the docs :slightly_smiling_face:
