### ISSUE TITLE
Make inheritance of members from the parent class configurable when inspecting

### ISSUE THREAD

**Issue by tazend** [mkdocstrings/griffe#153]
Hi,

**Is your feature request related to a problem? Please describe.**
I'm developing a Cython project and therefore parsing the source-code directly in order to generate documentation (which is what the `Visitor` does if I'm correct) is not possible.
Thus, the only way is via inspecting.

However, the problem I encountered is that when inspection is done, Members of the Parent are also shown in the documentation for the class.
For example, consider the following:

```python
class Test(dict):
    """Inherit from dict"""

    def __init__(self):
        pass

    def test_func(self):
        """test_func"""
        pass


class Blaa(Exception):
    """Test exception"""
    def __init__(self):
        pass
```

It will render like this:

![image](https://user-images.githubusercontent.com/75485188/235888116-237be425-b18a-46ca-a65c-d66414558dc8.png)

As the screenshot shows, any public function of the parent is also included.

**Describe alternatives you've considered**
Not really any good alternative when it comes to Cython projects, because everything is compiled and inspecting is the only way.

**Describe the solution you'd like**
I feel for Inspection, this should be configurable. Configurable because sometimes it might make sense to include the functions from the Parent class.
I found [this issue](https://github.com/mkdocstrings/mkdocstrings/issues/78) which essentially wants just that: inheriting from the parent (which is not yet possible when `visiting` the source-code directly instead of `inspecting`, since the `inherited_members` functionality is [not yet implemented in mkdocstrings](https://github.com/mkdocstrings/mkdocstrings/issues/78#issuecomment-1511013734) if I got that right)
So, for those that would want to inherit the members, forcing inspection instead of visiting the source-code would be an option (although source-code snippets wouldn't show up anymore)

However in other cases, for example when inheriting from something like `dict` it doesn't really make much sense in my view. The user is already notified that it inherits from `dict` (by showing `Bases: dict` at the top), and should therefore look at the documentation for the `dict` class instead.

Now what I don't know: When `inherited_members` is supported in `mkdocstrings`, and I would set it to `false`, would I get the desired functionality I am describing here? (for both inspection and visiting) i.e. public functions of the parents wouldn't show up?
If that would be the case, well then I guess its just a matter of time when it gets supported, and probably nothing must be changed in `griffe` directly.

I poked around a bit in the source code and found a way to disable the inheritance of members when inspecting, by adding another condition in the `_pick_members` function in `src/griffe/agents/nodes.py`:

```python
    def _pick_member(self, name: str, member: Any) -> bool:
        return (
            name not in self.exclude_specials
            and member is not type
            and member is not object
            and id(member) not in self._ids
            # Only include it if this is really a member of the current object
            and name in vars(self.obj)
        )
```

I figured that `self.obj` will always be of kind `module` or `class` when it collects the children of the node, and if the member is not directly a part of `vars(self.obj)`, then it is probably inherited.
So the difference is: `inspect.getmembers(self.obj)` always returns all the members including the inherited ones for a class, but `vars(self.obj)` does not include the inherited ones. So we can just check if the member is actually in `vars(self.obj)`.
If the check is added and I rebuild the documentation, then all the inherited members go away.

Not sure if this is the best way to go about it, but that was the solution I found (excluding the fact that `inherited_members` may already handle this anyway)

What do you think about this?

**Comment by pawamoy** [comment]
Hello @tazend, very good analysis! Thanks for the snippet using `vars`, that might be useful indeed.

A few corrections:

> So, for those that would want to inherit the members, forcing inspection instead of visiting the source-code would be an option (although source-code snippets wouldn't show up anymore)

Unfortunately there's no way to enforce inspection right now, unless using the Griffe "hybrid" extension which is not yet properly documented, and still very much experimental. Also, inspecting non-compiled modules does not prevent showing the source (`inspect` is able to find it for almost any given object :+1:).

I agree with all the rest.

> When inherited_members is supported in mkdocstrings, and I would set it to false, would I get the desired functionality I am describing here? (for both inspection and visiting) i.e. public functions of the parents wouldn't show up?

Yes! Ideally we'll be able to configure both visit and inspection the same way for inheritance. Saying `inherited_members: false` will remove inherited members from the serialized objects.

---

Proper inheritance support in Griffe is a top priority. Doing my best to move forward, *lots* of work to do so it takes time, but we'll get there :slightly_smiling_face:
