### ISSUE TITLE
Expression.full() errors if any Expressions inside it

### ISSUE THREAD

**Issue by machow** [mkdocstrings/griffe#163]
**Describe the bug**

For griffe v0.28.1, when `Expression.full()` gets called, if it contains any expressions within it, then it attempts to call `.canonical` on them, which produces an AttributeError:

```
AttributeError: 'Expression' object has no attribute 'canonical'
```

Here's an example that I used to check against:

```python
a: Union[list[str], str]
```

**Comment by pawamoy** [comment]
Damn, how am I not detecting this with the tests suite yet. Thanks for the report, will fix asap

**Comment by machow** [comment]
No worries! I was able to fix pretty fast and submit a PR in a sec! (No worries if you end up fixing another way)
