### ISSUE TITLE
Fails to recognize optional arguments in NamedTuple

### ISSUE THREAD

**Issue by OpenBagTwo** [mkdocstrings/griffe#165]
## Summary
`NamedTuples` with optional / default values still show as "required"

## Environment and Version
- Python 3.11.3, running on Linux x86-64
- mkdocs=1.4.3=pyhd8ed1ab_0
- mkdocs-autorefs=0.4.1=pyhd8ed1ab_1
- mkdocs-material=9.1.12=pyhd8ed1ab_0

## Steps to Reproduce

Since Python 3.7 (I think?) one can define a `NamedTuple` with default values as so:

```python
from typing import NamedTuple


class Example(NamedTuple):
    """A simple example of the autorefs bug

    Parameters
    ----------
    required : int
        A required value
    optional : float, optional
        An optional value, default is -3.6
    """

    required: int
    optional: float = -3.6
```

which behaves as follows:

```python
>>> Example(2)
Example(required=2, optional=-3.6)
```

Rendering this code with `mkdocstrings-python` results in the following:
![Screengrab from mkdocs output](https://github.com/mkdocstrings/autorefs/assets/66568922/7718b319-72a8-462f-9daa-064c8af12e0b)

## Workaround

Not that I've been able to figure out (besides just not using `NamedTuple`)

## Severity

Annoying.

## Desired Outcome

Fix

## Urgency

None

**Comment by pawamoy** [comment]
Should be fixed, will release soon :slightly_smiling_face:
