### ISSUE TITLE
Deprecation warning with Python 3.12.0b4

### ISSUE THREAD

**Issue by juergenzimmermann** [mkdocstrings/griffe#179]
**Describe the bug**
Actually a hint, not really a bug: Experimenting with Python 3.12.0b4 gives 2 deprecation warnings:
* .venv\Lib\site-packages\griffe\agents\nodes\_values.py, line 21
* .venv\Lib\site-packages\griffe\agents\nodes\_docstrings.py", line 8

**Debug logs**
```console
$ mkdocs build -v
...
DEBUG    -  mkdocstrings: Using handler 'python'
INFO     -  DeprecationWarning: ast.Ellipsis is deprecated and will be removed in Python 3.14; use ast.Constant instead
              File "C:\Zimmermann\Python\Lib\warnings.py", line 529, in _deprecated
                warn(msg, DeprecationWarning, stacklevel=3)
              File "C:\workspace\python\flaskapp\.venv\Lib\site-packages\griffe\agents\nodes\_values.py", line 21, in
                from ast import Ellipsis as NodeEllipsis
INFO     -  DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
              File "C:\Zimmermann\Python\Lib\warnings.py", line 529, in _deprecated
                warn(msg, DeprecationWarning, stacklevel=3)
              File "C:\workspace\python\flaskapp\.venv\Lib\site-packages\griffe\agents\nodes\_docstrings.py", line 8, in
                from ast import Str as NodeStr
```

**To Reproduce**
Any project using mkdocs and mkdocstrings, but Python 3.12.0b4

**Expected behavior**
No (annoying) warning.

**System (please complete the following information):**
- `griffe` version: 0.32.0
- Python version: 3.12.0b4
- OS: Windows 11 Enterprise 22H2

**Comment by pawamoy** [comment]
Thanks for the heads up! I'm waiting for LXML to release its v5, compatible with Python 3.12, before I can actually run CI on 3.12. And I think LXML is waiting for 3.12.0 to be released :confused:

**Comment by pawamoy** [comment]
Ah, v4.9.3 actually provides wheels for Python 3.12, great! Will then fix this ASAP :slightly_smiling_face:

**Comment by juergenzimmermann** [comment]
@pawamoy Thank you for the immediate fix. It works fine.

**Comment by pawamoy** [comment]
Thanks for testing and confirming it works!
