### ISSUE TITLE
Ability to silence warnings (e.g. "Param does not appear in signature")

### ISSUE THREAD

**Issue by NowanIlfideme** [mkdocstrings/griffe#181]
## Is your feature request related to a problem? Please describe.

When building `mkdocstrings-python` with many classes (especially `Pydantic` classes) I get many warnings for:

> Parameter 'param_name' does not appear in the function signature

## Describe the solution you'd like

I'd very much like a way to silence this warning in particular. Probably a way to silence other warnings would be nice too.
That way I could run `mkdocs` in strict mode and check if it fails in CI.

## Describe alternatives you've considered

Currently just dealing with it, and getting the console spammed. 😄 

One possible other thing is to not create this warning when there are `**kwargs`, but I think most people would want it there by default anyways.

## Additional context

I'd be fine with being able to silence just this warning. I assume Pydantic support isn't something that will be worked on (likely living in an extension to Griffe or something?), which is fine. On a longer-term scale, it would probably be something that would be configured through `mkdocstrings`.

**Comment by pawamoy** [comment]
It's now fixed, you should be able to use `warn_unknown_params: false` to disable these warnings :slightly_smiling_face:
