### ISSUE TITLE
RecursionError when parsing monorepo and show_submodules is set to true

### ISSUE THREAD

**Issue by jorgegomezcq** [mkdocstrings/griffe#189]
**Describe the bug**

From conversations over Gitter regarding a `RecursionError` exception that is thrown when griffe tries to parse a monorepo.

**Traceback

GitHub does not allow pastes of a certain size inline so using external paste service:

https://paste.sr.ht/~whereiseveryone/0f385b290bf1f6550e499781c87af1d4253999c0

**System (please complete the following information):**
- `griffe` version: 0.32.4
- Python version: 3.9.17

- OS: Ubuntu

**Comment by pawamoy** [comment]
Sorry for the long delay.

After looking at the traceback again, I wonder if there's actually an issue or if the recursion depth is too low in your case.
Could you try to use https://docs.python.org/3/library/sys.html#sys.setrecursionlimit to increase it, for example (lets be crazy) to 10000, and see if the error still happens?

**Comment by pawamoy** [comment]
Closing for now, let me know if it still happens and I'll reopen :slightly_smiling_face:
