### ISSUE TITLE
Add __post_init__ as a place to look for attribute docstrings (labeling them as instance-attributes)

### ISSUE THREAD

**Issue by ssweber** [mkdocstrings/griffe#190]
**Is your feature request related to a problem? Please describe.**
I've converted many of my classes to dataclasses. I'd like to add docstrings to many of the attributes that are now added in `__post_init__` rather than `__init__` (since that's really where args/kwargs now live)

**Describe the solution you'd like**
Add `__post_init__` to two places in visitor.py that look for attribute docstrings

**Describe alternatives you've considered**
I looked at creating an extension, but was struggling to see how to make it work

**Comment by ssweber** [comment]
#191 

I only question if they should be labeled any different?

**Comment by ssweber** [comment]
Also: if you don’t like hard-coding `__post_init__`, maybe it could look for `__init__` and also any names in a config option?

 `add_attribute_docstrings_from` ?

**Comment by pawamoy** [comment]
Thanks for the request. Before reviewing your PR, isn't it possible to do something like this?

```python
@dataclass
class C:
    a: float
    """Docs for a."""
    b: float
    """Docs for b."""
    c: float = field(init=False)
    """Docs for c."""

    def __post_init__(self):
        self.c = self.a + self.b
```

**Comment by ssweber** [comment]
That's really interesting. I'm still wrapping my head around the edge-cases of dataclasses (I have a conflicting field function, so I import `field` as `field_`

Using that, it labels `c` as a class-variable, which it isn't. I poked around at how to correct that in visitor.py, but I didn't get too far.

```
    c: float = field_(init=False)
    """Docs for c."""
    d: float = field_(default=1.0, init=False)
    """Docs for d."""

    def __post_init__(self):
        self.c = self.a + self.b
```
**docstring as suggested:**

> ![before_patch](https://github.com/mkdocstrings/griffe/assets/57631333/89df2a89-1a5f-44ff-a69f-a2fee91602cc)

**docstring as suggested, after pr**
> ![after_patch](https://github.com/mkdocstrings/griffe/assets/57631333/dc695049-e5c2-4423-8253-20f84050fb50)

**docstring in `__post_init__`, after pr**
```
    d: float = field_(default=1.0, init=False)
    """Docs for d."""

    def __post_init__(self):
        self.c = self.a + self.b
        """Docs for c."""
```
> ![docstring_in_post_init](https://github.com/mkdocstrings/griffe/assets/57631333/aed77dc9-32f9-4160-b76c-3d7b4c327bf6)

**Comment by pawamoy** [comment]
Thanks for the detailed answer :slightly_smiling_face: 

The issues you point at are fixable, but not until I've finished improving expressions in Griffe.
So I think it's best to go with your PR for now.

**Comment by ssweber** [comment]
Let me see how to fix this though (see how a gets overwritten):

```
@dataclass
class Test:
    a: int
    """Test doc"""
    b: int
    
    def __post_init__(self):
        self.c = a + b
        self.a = c + a
```

![image](https://github.com/mkdocstrings/griffe/assets/57631333/1a34d97a-feb2-4805-aa96-2399aaf87731)

**Comment by ssweber** [comment]
Ok! I just wanted to point it out, so it’s not an unexpected gotcha

**Comment by ssweber** [comment]
considering this `resolved` for now:

Use:
```
    c: float = field(init=False)
    """Docs for c."""
```

convention
