### ISSUE TITLE
Support output in the format of GitHub workflow commands

### ISSUE THREAD

**Issue by edgarrmondragon** [mkdocstrings/griffe#192]
**Is your feature request related to a problem? Please describe.**

I'm interested in using `griffe check` in CI (in pull requests and/or before releases) to get warnings about breaking changes in a library's API. I already output annotations for test failures using [`pytest-github-actions-annotate-failures`](https://github.com/pytest-dev/pytest-github-actions-annotate-failures) and other tools, such as [Ruff](https://github.com/astral-sh/ruff), already support output in this format.

**Describe the solution you'd like**

For a result like this

```console
$ griffe check my_package -a 1.2.0
my_package/enums.py:8: StringEnum: Public object was removed
my_package/client.py:96: Client.USER_AGENT: Public object was removed
```

I would like to be able to output it in the [GitHub workflow command](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message) format:

```console
$ griffe check my_package -a 1.2.0 --format=github  # suggested CLI option
::warning file=my_package/enums.py,line=8,title=StringEnum::Public object was removed
::warning file=my_package/client.py,line=96,title=Client.USER_AGENT::Public object was removed
```

**Describe alternatives you've considered**

* I could try to parse the existing non-verbose output and wrangle it into the desired format
* I could create a comment in the PR with the existing output format

**Additional context**

For example, this is how files are annotated when using `pytest-github-actions-annotate-failures`:
<img width="1205" alt="Screenshot 2023-07-30 at 19 25 52" src="https://github.com/mkdocstrings/griffe/assets/16805946/7e869f6b-f4d8-46d3-a287-e29c5d647e7d">

**Comment by pawamoy** [comment]
Thanks for the request, I like the idea :slightly_smiling_face:
I'll try to get to it soon.

**Comment by edgarrmondragon** [comment]
Thanks @pawamoy. One potential caveat is that `griffe check` seems to annotate lines in the _againts_ ref, while GitHub annotations always point to the current code.

**Comment by pawamoy** [comment]
I believe that's only an issue for removed objects, and I don't see another way to do that, unless we say line number is 0 for removed objects?

**Comment by edgarrmondragon** [comment]
> I believe that's only an issue for removed objects, and I don't see another way to do that, 

I see, you're right.

> unless we say line number is 0 for removed objects?

Yeah, that's a good solution 👍

**Comment by pawamoy** [comment]
By the way this was implemented for insiders: https://mkdocstrings.github.io/griffe/checking/#github
