### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/griffe#2]
Call to freelancers! I would like a logo for griffe. What I have in mind is this: black and white, thick lines, one or two vulture claws grabbing "GRIFFE" from the sky, with the blinding light of the sun behind them.

For the light, I was thinking using straight lines like this:
![image](https://user-images.githubusercontent.com/3999221/146657663-e59c3faf-a284-4009-8b88-6677bc6004b5.png)
But there are probably other ways to give this effect of high contrast and strong light.

**Comment by pawamoy** [comment]
Something like this: https://www.pinterest.com/pin/853361829370436779/
![claws](https://user-images.githubusercontent.com/3999221/153765627-52b49ef4-d21e-4367-affe-17cff5bfb92e.png)

**Comment by francois-rozet** [comment]
Hey, I'm not a good drawer but I can play with vector graphics and I've made a few logos in the past. I like very sober designs as they are easier to remember and still look nice as icons.

So I thought of a snake (a python) scratched by a claw (griffe). I quickly made it. I added small artefacts along the scratches to give an impression of movement/speed.

![griffe_6](https://user-images.githubusercontent.com/37352336/163880030-abf9b5e7-312d-4ddc-bdce-7795ff87a7c9.png)

At the end, its not obvious that these are claw scratches (it kinda looks like ink), but I still like it. If you don't use it, I'll probably ahah.

An much less sober alternative, would be

![griffe_4](https://user-images.githubusercontent.com/37352336/163880276-926db05d-777c-4faa-83b1-9d8b028c56d1.png)

but, I'm not 100% sure it is legal, as it reproduces an image I found somewhere on the internet, without copyright notice.

**Comment by pawamoy** [comment]
Wow, that's great!

Yeah I had trouble figuring out the first drawing, but once you do it's pretty nice :smile: 
The second is one is indeed less sober haha. I'd prefer a vulture rather than an eagle though (eagle bears too much meaning IMO).

I have a very precise image of what I want in my head, but honestly I don't have the skills to draw it, so I'd be fine with what you proposed.

**Comment by francois-rozet** [comment]
Well there is nothing urgent, so we can wait for someone that can draw what you want. If you are tired of waiting, ping me and I'll send you the raw (svg) files.

**Comment by pawamoy** [comment]
ping :smile: 

I'd like to use the first one if that's OK with you!

**Comment by francois-rozet** [comment]
Hello, fine by me! I sent you the file by e-mail 📫

**Comment by francois-rozet** [comment]
No problem! IMO, it is not big enough of a contribution to be credited in the README, but you can put me as co-author in the commit (Co-authored-by: François Rozet <francois.rozet@outlook.com>) message.

**Comment by pawamoy** [comment]
Very well! I'll put your name in the `alt` field of the image as well, so it appears in the HTML.

**Comment by pawamoy** [comment]
OK, this is **awesome**. I freaking love it! https://mkdocstrings.github.io/griffe/
Thank you so much!!! :heart: :rocket:

**Comment by pawamoy** [comment]
Ah, the logo is not rendered on GitHub... I guess I'll have to invert the symlink and file locations.
