### ISSUE TITLE
Google-style `Example:` `>>>` code blocks not rendering correctly

### ISSUE THREAD

**Issue by glenn-jocher** [mkdocstrings/griffe#201]
**Describe the bug**
Google-style `Example:` `>>>` code blocks not rendering correctly in mkdocs using mkdocsmaterial with mkdocstrings. 

#### Original socstring

<img width="930" alt="Screenshot 2023-08-20 at 17 19 23" src="https://github.com/mkdocstrings/griffe/assets/26833433/f27c1df7-c74b-4a0a-8c8e-01348fc10244">

#### Mkdocs serve results

<img width="1432" alt="Screenshot 2023-08-20 at 17 14 10" src="https://github.com/mkdocstrings/griffe/assets/26833433/00bb56a0-8c24-4d0b-b877-5b36158292d4">

My `plugins` section of mkdocs.yaml looks like this:

```yaml
plugins:
  - search
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
```

```console
$ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
WARNING  -  Both index.md and README.md found. Skipping README.md from /Users/glennjocher/PycharmProjects/ultralytics/docs
INFO     -  Documentation built in 47.42 seconds
```

**To Reproduce**

Build docs with this example function:

```python
class RTDETRTrainer:
    """
    A class extending the DetectionTrainer class for training based on an RT-DETR detection model.

    Notes:
        - F.grid_sample used in rt-detr does not support the `deterministic=True` argument.
        - AMP training can lead to NaN outputs and may produce errors during bipartite graph matching.

    Example:
        >>> from ultralytics.models.rtdetr.train import RTDETRTrainer
        >>> args = dict(model='rtdetr-l.yaml', data='coco8.yaml', imgsz=640, epochs=3)
        >>> trainer = RTDETRTrainer(overrides=args)
        >>> trainer.train()
    """
```

**Expected behavior**

Expect code to render correctly with python highlights.

**System (please complete the following information):**
- `griffe` version: 0.32.1
- Python version: 3.11
- OS: Linux

**Comment by pawamoy** [comment]
Thanks for the report!

PyCon code blocks are only recognized in `Examples` section (plural), not in `Example` ones (which are parsed and rendered as admonitions). This is documented here: https://mkdocstrings.github.io/griffe/docstrings/#examples.

In the future such code blocks will be recognized anywhere thanks to a Markdown extension. This is in our backlog, therefore I'll close this issue :slightly_smiling_face:
