### ISSUE TITLE
Get class parameters from parent's __init__

### ISSUE THREAD

**Issue by machow** [mkdocstrings/griffe#205]
**Is your feature request related to a problem? Please describe.**

Currently, griffe checks Class.members, when fetching Class.parameters. When the `__init__` is inherited from the parent class, this means that an empty set of parameters gets returned.

**Describe the solution you'd like**

WDYT of checking in `Class.inherited_members` as well, in order to get parameters for classes that don't override `__init__`?

**Comment by pawamoy** [comment]
Yep, good idea! We can check both at once using [`Class.all_members`](https://mkdocstrings.github.io/griffe/reference/griffe/#griffe.Class.all_members) :slightly_smiling_face: Feel free to send a PR, otherwise I'll get to it soon (it's an easy change, shouldn't take long).

**Comment by pawamoy** [comment]
(by the way, I think mkdocstrings-python also checks only in members for `__init__` when merging docstring, will open an issue there tomorrow)
