### ISSUE TITLE
class attribute has label 'instance-attribute'

### ISSUE THREAD

**Issue by ixje** [mkdocstrings/griffe#227]
### Description of the bug
I'm trying to figure out how to differentiate between a class attribute and an instance attribute.
A module attribute gets the label `module-attribute`, but a class attribute and instance attribute both get `instance-attribute` as label.

### To Reproduce
**sample.py**
```python
module_attr: float

class MyClass:
    #: my class attribute docstring
    myclass_attribute: float

    def __init__(self):
        self.my_instance_attribute: float
```
**main.py**
```python
import griffe

def print_attrs(members):
    for v in members.values():
        if isinstance(v, griffe.Attribute):
            print(v.name, v.labels)
        if isinstance(v, griffe.Class):
            print_attrs(v.members)

sample = griffe.load("sample")
print_attrs(sample.members)
````

**output**
```bash
my_module_attr {'module-attribute'}
myclass_attribute {'instance-attribute'}
my_instance_attribute {'instance-attribute'}
```

### Expected behavior
Expected that `myclass_attribute` would have the label `class-attribute`.

### Environment information
- __System__: macOS-14.0-x86_64-i386-64bit
- __Python__: cpython 3.11.4
- __Environment variables__:
- __Installed packages__:
  - `griffe` v0.38.1

**Comment by pawamoy** [comment]
OK, so IMO it makes sense:

- if your class attribute does not have a value (only an annotation), users cannot access it at runtime on the class, so no `class-attribute` label
- however, Griffe expects that its value will be set in the `__init__` method (either explicitly or thanks to dataclasses for example), therefore it sets the `instance-attribute` label. 

Let me know what you think. In the meantime I'll close this issue as I think the behavior is correct as it is.

**Comment by ixje** [comment]
I agree with your analysis. Most important for me was realizing that a value must be assigned before `__init__` for it to be labelled as `class-attribute`
