### ISSUE TITLE
docs: bad link

### ISSUE THREAD

**Issue by AntoineD** [mkdocstrings/griffe#242]
On griffe's docs, for instance [here](https://mkdocstrings.github.io/griffe/reference/griffe/extensions/), the link for [View the source of this page](https://github.com/media/data/dev/insiders/griffe/src/griffe/extensions/__init__.py) points to a page that only contains `Not found`.

**Comment by pawamoy** [comment]
Oh wow, these are my local paths :rofl: Thanks for the heads up! Will fix right now.

**Comment by pawamoy** [comment]
And it actually affects all my docs pages :scream: I wonder if this is a change in mkdocs-gen-files :thinking:

**Comment by pawamoy** [comment]
This is fixed, thanks again :slightly_smiling_face:
