### ISSUE TITLE
feature: allow plugins to extend json output

### ISSUE THREAD

**Issue by patrick91** [mkdocstrings/griffe#291]
Hi there!

I was trying to write a plugin that prints the default values and type annotations as strings[1] (instead of a dump of the "ast") so I can show them on my website's docs, but by looking at the source code of Griffe, I don't think this is possible, am I correct? 😊

[1] Also, maybe there's a built-in way to do this, but I haven't found it 😊

**Comment by pawamoy** [comment]
Hi @patrick91!

I'm not sure exactly what you mean by "show them your website's docs". It's true that the JSON dump only include the expressions (which are ASTs indeed), and not the string representation. If you have access to the runtime objects though, it's simply a matter of doing `str(expr)` to get back source code :)

If you can only work with the JSON (could you share why? I'm curious), we can definitely consider adding the string representation of expressions in the JSON data :)

I'm also very open to discuss adding extension hooks! I'm super curious to see what use-cases people with come up with for extensions :) Here it's probably simpler to update Griffe's serializer though :)

**Comment by patrick91** [comment]
thanks for the reply! I should have mentioned this, but I'm working with the JSON directly because my website is built with Astro ^^

While working on it I implemented a tiny component that converts the expression to a string, it was quite simple, so maybe this issue is not that useful anymore? I do think it would be useful to add more data to the JSON (or customise the output, I'm exporting everything and the JSON is quite big, but that's a minor issue)

Also, I'm using `typing.Doc` so my code to print the expression has some check for removing the `Annotated` to make

**Comment by pawamoy** [comment]
Great! Well I guess we can close this then. The string repr won't help at all if you need to unwrap `Annotated` indeed. Do create a new issue or discussion if you'd like to discuss about JSON output customization!
