### ISSUE TITLE
bug: Enum members mis-labelled as instance attributes

### ISSUE THREAD

**Issue by butterlyn** [mkdocstrings/griffe#292]
### Description of the bug
When adding a attribute annotation to members of a Enum class, they are rendered with the label "instance-attribute" and "class-attribute". Instance attribute would ideally be omitted by default for Enum members, since Enum classes are not instantiated.

### To Reproduce

```python
from enum import Enum

class MyEnum(Enum):
    FIRST_MEMBER = 1
    """The first enumeration member."""

    SECOND_MEMBER = 2
    """The second enumeration member."""
```

### Expected behavior
`FIRST_MEMBER` and `SECOND_MEMBER` labelled in MkDocs as a "class-attribute" only

### Additional context
I'm currently getting around this issue by type-hinting all the enum members with `typing.ClassVar`.

**Comment by pawamoy** [comment]
At runtime they're actually instance attributes too:

```pycon
>>> from enum import Enum
>>> class MyEnum(Enum):
...     FIRST_MEMBER = 1
...     SECOND_MEMBER = 2
... 
>>> first = MyEnum.FIRST_MEMBER
>>> isinstance(first, MyEnum)
True
>>> first.SECOND_MEMBER
<MyEnum.SECOND_MEMBER: 2>
```

**Comment by butterlyn** [comment]
That's... pretty cool. Thanks for enlightening me

**Comment by pawamoy** [comment]
That's cool and... sometimes confusing :sweat_smile: I've seen Python devs with many years of experience strongly recommend against enumerations. And I'm starting to understand why. They just complicate things most of the time (different `str` and `repr` output, having to access the actual value with `.value`, they're not JSON-serializable by default, etc.). It's generally easier to have a simple class with regular class attributes:

```python
class MyEnum:
    FIRST_MEMBER = 1
    SECOND_MEMBER = 2
```

But anyway, that's just my experience :smile:
