### ISSUE TITLE
bug: Wrong alias target path when inspecting class, causing stubs-merging to fail silently

### ISSUE THREAD

**Issue by tlambert03** [mkdocstrings/griffe#296]
### Description of the bug

Hey @pawamoy.  I'm back working on updating docs for one of my packages to work with the latest griffe.  (I've been using a [griffe fork](https://github.com/tlambert03/griffe/tree/recursion) for this specific package back since https://github.com/mkdocstrings/griffe/pull/115 and I'm trying to get off of it.  This isn't exactly the same issue, but basically i'm still struggling to get griffe/mkdocstrings to find and inject the stubs provided in a pyi file.  I just spent an hour or two trying to debug it, and i'm stumped.  as best as I can tell, griffe *does* find all the members/methods, but mkdocs strings only shows 3 of them.

### To Reproduce

 ```
mkdir example
cd example
python -m venv .venv
 . .venv/bin/activate
pip install mkdocs-material mkdocstrings-python pymmcore
cat <<EOF > mkdocs.yml
site_name: My Docs
theme:
  name: material
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            find_stubs_package: true
EOF
mkdir docs
echo "::: pymmcore.CMMCore" > docs/index.md
mkdocs serve
 ```

### screenshot

This class has a ton of methods, all of which are documented in the stub file, but only a handful are found.

<img width="602" alt="Screenshot 2024-06-22 at 7 02 11 PM" src="https://github.com/mkdocstrings/mkdocstrings/assets/1609449/e131ddd1-8237-41d2-a632-728e4c868a18">

For what it's worth, the stubs i want it to find are at the top level `__init__.pyi`

```sh
➜ tree -L 3 .venv/lib/python3.12/site-packages/pymmcore
.venv/lib/python3.12/site-packages/pymmcore
├── __init__.py
├── __init__.pyi
├── _pymmcore_swig.cpython-312-darwin.so
├── _version.py
├── py.typed
├── pymmcore_swig.i
└── pymmcore_swig.py
```

(however, I have also tried moving them to other places including `_pymmcore_swig.pyi`, etc...
If you want to quickly see the stubs, they are [here](https://github.com/micro-manager/pymmcore/blob/main/src/pymmcore/__init__.pyi) 

### Expected behavior
find all the methods

### Environment information
```
➜ python -m mkdocstrings.debug
- __System__: macOS-14.5-arm64-arm-64bit
- __Python__: cpython 3.12.3 (/Users/talley/dev/self/example/.venv/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings` v0.25.1
```

**Comment by tlambert03** [comment]
> allow_inspection=False

amazing, i'm sorry i missed that.  indeed setting that gets me *much* farther!  now we're finding everything:

<img width="1008" alt="image" src="https://github.com/mkdocstrings/mkdocstrings/assets/1609449/211e5671-9a6c-40bc-8bcb-96c98d136985">

And inheritance is working great using something like this:

```yaml
         options:
           preload_modules: [pymmcore]
           allow_inspection: false
           inherited_members: true
```

This may very well suffice for my needs.  But now that you've pinpointed the more interesting guts of it all, I'm going to step back a bit and re-evaluate a) how I'm designing my docs and b) whether there's anything I can contribute to improve the state of things.

You've put much more time into this than expected, thanks so much.  Feel free to put it on the back-burner until I check in again (unless you've found some things that you definitely want to work on here)

**Comment by pawamoy** [comment]
I took a couple slow days, so I guess I was energized enough to actually write down my whole investigation :joy: No problem at all, I like hunting bugs :slightly_smiling_face: If `allow_inspection` is all you need, that's perfect to me! If you still want to improve the state of things regardless, you can look into swig internals to see if it's possible to add `__module__` attributes to methods too (I'd be curious to know that). Other than that, yes, I already have a fix for the wrong alias target paths, and will probably also work on supporting `a.b` vs. `a._b` too (though not with a high priority).

**Comment by tlambert03** [comment]
minor note about swig while looking into this.  I was at least able to determine what is "special" about the few `staticmethods` that do show up. Here is a section of the `swig_wrap.cpp` file that swig generates when building the c-extension for pymmcore:

```cpp
SWIGINTERN PyMethodDef SwigPyBuiltin__CMMCore_methods[] = {
  { "noop", (PyCFunction)(void(*)(void))_wrap_CMMCore_noop, METH_STATIC|METH_NOARGS, "noop()" },
  { "enableFeature", (PyCFunction)(void(*)(void))_wrap_CMMCore_enableFeature, METH_STATIC|METH_VARARGS, "\n"
		"enableFeature(char const * name, bool enable)\n"
		"\n"
		"Parameters\n"
		"----------\n"
		"name: char const *\n"
		"enable: bool\n"
		"\n"
		"" },
  { "isFeatureEnabled", (PyCFunction)(void(*)(void))_wrap_CMMCore_isFeatureEnabled, METH_STATIC|METH_O, "\n"
		"isFeatureEnabled(char const * name) -> bool\n"
		"\n"
		"Parameters\n"
		"----------\n"
		"name: char const *\n"
		"\n"
		"" },
  { "loadDevice", _wrap_CMMCore_loadDevice, METH_VARARGS, "\n"
		"loadDevice(CMMCore self, char const * label, char const * moduleName, char const * deviceName)\n"
		"\n"
		"Parameters\n"
		"----------\n"
		"label: char const *\n"
		"moduleName: char const *\n"
		"deviceName: char const *\n"
		"\n"
		"" },
```
`SwigPyBuiltin__CMMCore_methods` is an array of [`PyMethodDef` structes](https://docs.python.org/3/c-api/structures.html#c.PyMethodDef).  The second item in the struct is supposed to be a [`PyCFunction`](https://docs.python.org/3/c-api/structures.html#c.PyCFunction)... but as you can see, only the first three static methods (`noop`, `enableFeature`, and `isFeatureEnabled`) actually are... which explains why they showed up in the screenshot in the original post.

all the other are simply defined as `PyObject`.  such  as the first one for the `loadDevice` method:

```cpp
SWIGINTERN PyObject *_wrap_CMMCore_loadDevice(PyObject *self, PyObject *args) { ...
```

so, it would appear that swig isn't generating a proper method definition 🤷

**Comment by pawamoy** [comment]
Ah, super interesting, thanks! So, supposedly, if it generated all the methods the same way, casting them with `(PyCFunction)(void(*)(void))`, they would all get a `__module__` attribute, allowing Griffe to function properly. But maybe `PyCFunction` is only meant for staticmethods, which the rest are not? Well, I'm out of my depth here :sweat_smile:

**Comment by tlambert03** [comment]
yep, I'm out of my depth as well... however, it does seem based on that C-Python docs for [`PyMethodDef`](https://docs.python.org/3/c-api/structures.html#c.PyMethodDef) (and indeed it fits with my understanding of methods) that all methods, and not only static methods, are regular python functions (not just Callable, but actually type `FunctionType` or `BuiltinFunctionType`).  that's obviously not to say that all callable objects on a class must be methods, they can also be descriptors or many other types, so swig isn't doing anything illegal (outside of declaring that array to be an array of `PyMethodDef`?)

```python
In [8]: from types import BuiltinFunctionType

In [9]: isinstance(pymmcore.CMMCore.enableFeature, BuiltinFunctionType)
Out[9]: True

In [10]: isinstance(pymmcore.CMMCore.__init__, BuiltinFunctionType)
Out[10]: False

In [11]: type(pymmcore.CMMCore.enableFeature)
Out[11]: <class 'builtin_function_or_method'>

In [12]: type(pymmcore.CMMCore.__init__)
Out[12]: <class 'wrapper_descriptor'>
```


relevant sections of the swig source code:
- https://github.com/swig/swig/blob/ce2bb71a486bd575afb3c19ef98aae5f5e147905/Source/Modules/python.cxx#L4696-L4722
- https://github.com/swig/swig/blob/ce2bb71a486bd575afb3c19ef98aae5f5e147905/Source/Modules/python.cxx#L4092-L4093
- and here, where `PyObject` is chosen rather than `PyCFunction`: https://github.com/swig/swig/blob/ce2bb71a486bd575afb3c19ef98aae5f5e147905/Source/Modules/python.cxx#L5116-L5120

**Comment by pawamoy** [comment]
I've pushed two bug fixes :relieved: They will make it to the next 0.x version. I believe we can close this now :slightly_smiling_face:

**Comment by tlambert03** [comment]
wow, great work!  definitely fixes this issue 👍

**Comment by pawamoy** [comment]
You confirm this works well even with `allow_inspection=True`?

**Comment by tlambert03** [comment]
i was just trying my original example here and seeing all the new stuff it found.  however, for posterity.  here is what i get with `allow_inspection: true`

<img width="921" alt="Screenshot 2024-06-26 at 1 51 44 PM" src="https://github.com/mkdocstrings/griffe/assets/1609449/dfefe182-fdb3-46af-b71c-bef9f5ecb9dd">

and with `allow_inspection: false` (where it sees my stubs and stops)

<img width="965" alt="Screenshot 2024-06-26 at 1 53 12 PM" src="https://github.com/mkdocstrings/griffe/assets/1609449/6d87f625-73f1-4d77-a281-a072cddf8175">

**Comment by pawamoy** [comment]
Perfect, thanks for confirming!
