### ISSUE TITLE
bug: Yields broken for properties

### ISSUE THREAD

**Issue by michprev** [mkdocstrings/griffe#298]
### Description of the bug
griffe complains with `No type or annotation for yielded value 1` when using `Yields:` together with properties.

Both removing `@property` or changing `Yields:` to `Returns:` works but results in different code or rendered docs.

### To Reproduce

```python
@property
def children(self) -> Iterator[EnumValue]:
    """
    Yields:
        Direct children of this node.
    """
    yield from self._values
```
where
```python
_values: List[EnumValue]
```

### Full traceback

Relevant info:
```console
WARNING -  griffe: wake/ir/declarations/contract_definition.py:357: No type or annotation for yielded value 1
WARNING -  griffe: wake/ir/declarations/enum_definition.py:109: No type or annotation for yielded value 1
WARNING -  griffe: wake/ir/declarations/error_definition.py:94: No type or annotation for yielded value 1
...
```

Full log from `mkdocs build -v`:

[log.txt](https://github.com/user-attachments/files/16011674/log.txt)

### Expected behavior

griffe works with properties yielding values as expected.

### Environment information

```bash
griffe --debug-info

- __System__: macOS-14.5-arm64-arm-64bit
- __Python__: cpython 3.12.2 (/Users/michal/.pyenv/versions/3.12.2/bin/python3.12)
- __Environment variables__:
- __Installed packages__:
  - `griffe` v0.47.0
```

**Comment by pawamoy** [comment]
Hi @michprev, thanks for the report.

It's actually the first time (I think) that I encounter a property that is also a generator :smile: Mind blown a bit!

I suppose the issues comes from the fact that when we parse a Yields section, we expect the parent to be a function and not an attribute. It should be easy to fix :slightly_smiling_face:
