### ISSUE TITLE
backports.strenum dependency missing in conda package

### ISSUE THREAD

**Issue by analog-cbarber** [mkdocstrings/griffe#307]
The conda package for griffe does not include a dependency for backports.strenum for python less than 3.11.
As a result you will get an error like this if installed using conda with python 3.10:

```
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/mkdocstrings_handlers/python_xref/__init__.py", line 18, in <module>
    from .handler import PythonRelXRefHandler
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/mkdocstrings_handlers/python_xref/handler.py", line 24, in <module>
    from griffe.dataclasses import Object
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/griffe/__init__.py", line 27, in <module>
    from _griffe.agents.inspector import Inspector, inspect
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/_griffe/agents/inspector.py", line 12, in <module>
    from _griffe.agents.nodes.runtime import ObjectNode
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/_griffe/agents/nodes/runtime.py", line 10, in <module>
    from _griffe.enumerations import ObjectKind
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/_griffe/enumerations.py", line 12, in <module>
    from backports.strenum import StrEnum
ModuleNotFoundError: No module named 'backports'
```
 
The workaround is to install `backports.strenum` separately.

The easiest fix would be to just make that an unconditional dependency. Another easy fix would 
be to just inherit from `str, enum.Enum` instead of `StrEnum`.

**Comment by pawamoy** [comment]
Thanks @analog-cbarber. Do you mean that `backports.strenum` *doesn't exist* in Conda, and therefore cannot be added as a dependency to Conda's Griffe package? Because otherwise, I would say that maintainers of the Conda package should update its dependencies :thinking: 

> The easiest fix would be to just make that an unconditional dependency

If that's only a short-term workaround, why not, that seems reasonable. 

> Another easy fix would be to just inherit from str, enum.Enum instead of StrEnum.

I'm actually a novice regarding `StrEnum`. I just saw that, by inheriting from `StrEnum` instead of `Enum`, I could compare enumeration values with their actual string values:

```python
Kind.MODULE == "module"  # works with StrEnum, not Enum
```

Would inheriting from both `str` and `Enum` have the same effect? If yes, then that seems like the best solution going forward!

**Comment by analog-cbarber** [comment]
`backports.strenum` exists in conda. The problem is that it is not being included in the conda dependency list for griffe in python 3.10 so why you install griffe (or anything that depends on it), you won't get the backports package.

I think the conditional dependency in your pyprojects.toml file works ok for the wheel, but conda does not have conditional dependencies in runtime packages. So to properly handle conditional cases for conda you need to build a package for each python version. Probably not worth the trouble just for this one little library.

As for `StrEnum` it is nice to have when you are using 3.11 or later, but it works perfectly well to inherit from both `str` and `enum.Enum`, but you have to put `str` first:

```python
>>> class E(str, enum.Enum):
    A = "a"
    B = "b"
    
>>> E.A == "a"
True
```

**Comment by pawamoy** [comment]
Well, Griffe is far from being the only package with conditional dependencies, so I wonder how Conda usually handles that 🤔

In this case it seems we have an easy fix on Griffe's side, so I'll consider sparing the trouble to the Conda package maintainers 🙂

Also, I've opened a few issues there, let see what they say!

**Comment by analog-cbarber** [comment]
If you really need conditional dependencies on python version, then you just have to build a separate conda package for each python version instead of a universal python noarch package. The recipe itself can have conditional dependencies, you just have to build it for each version.

**Comment by pawamoy** [comment]
Got it, thanks!

**Comment by pawamoy** [comment]
Turns out they simply added the dependency unconditionally. If that was what you suggested when you wrote:

> The easiest fix would be to just make that an unconditional dependency.

...then sorry, I misunderstood and thought you meant to do that in Griffe directly.

**Comment by pawamoy** [comment]
OK the only difference I could find between `MyEnum1(str, Enum)` and `MyEnum2(StrEnum)` is this:

```pycon
>>> str(MyEnum1.a)
'MyEnum1.a'
>>> str(MyEnum2.a)
'a'
```

...which I think is OK. I'll make the change.
