### ISSUE TITLE
feature: stable `as_json`

### ISSUE THREAD

**Issue by patrick91** [mkdocstrings/griffe#310]
Hi there! I have not investigated this much, but looks like using `as_json` doesn't always return the same data (or at least not in the same order) see this diff: https://github.com/strawberry-graphql/strawberry.rocks/commit/fc70f2a1f42c8fd69ce213d8366a71e683be5827

For my use case I'll do some sorting, but I was wondering if this could be a feature of Griffe 😊

**Comment by pawamoy** [comment]
> 113,475 additions, 113,475 deletions not shown because the diff is too large. Please use a local Git client to view these changes. 

Ouch :sweat_smile: 

Yes that's a good idea, we can probably use `json.dumps(..., sort_keys=True)` :slightly_smiling_face:

**Comment by patrick91** [comment]
@pawamoy I was using sort_keys, but then the order of the members would change too, not sure why :D

**Comment by pawamoy** [comment]
Ah 🤔 I'll investigate.

**Comment by pawamoy** [comment]
Can you tell me (again? sorry if I forgot) how you dump and reload the data? Or just point me at the code you're using to dump/load?

**Comment by pawamoy** [comment]
I can't replicate the members dis-ordering issue across multiple invocations of Griffe :thinking:

**Comment by pawamoy** [comment]
Note that members are dumped in the *order they are found in the sources*. If you move objects around, the order in the JSON dump will also change :slightly_smiling_face:
