### ISSUE TITLE
bug: unsupported node

### ISSUE THREAD

**Issue by slyons** [mkdocstrings/griffe#316]
### Description of the bug
I'm trying to generate some documentation using mkdocstrings for a Rust/pyo3 project but am not able to due to the bug.

### To Reproduce
```
git clone https://github.com/slyons/szurubooru-client
git switch dev/pylib
cd szurubooru-client-docs
./build.sh
griffe dump szurubooru_client -o/dev/null -LDEBUG
```

### Full traceback
<details><summary>Full traceback</summary>

```python
INFO       Loading package szurubooru_client
DEBUG      Searching path(s) for szurubooru_client
DEBUG      Found szurubooru_client: loading
DEBUG      Loading path /opt/dev/projects/szurubooru-client/szurubooru-client/szurubooru_client/__init__.py
DEBUG      Loading path /opt/dev/projects/szurubooru-client/szurubooru-client/szurubooru_client/szurubooru_client.cpython-312-darwin.so
DEBUG      Loading path /opt/dev/projects/szurubooru-client/szurubooru-client/szurubooru_client/models.py
DEBUG      Failed to extract `__all__` value: szurubooru_client.models.__all__ at /opt/dev/projects/szurubooru-client/szurubooru-client/szurubooru_client/models.py:34: unsupported node <class 'ast.Attribute'>
DEBUG      Loading path /opt/dev/projects/szurubooru-client/szurubooru-client/szurubooru_client/tokens.py
DEBUG      Failed to extract `__all__` value: getattr(_tokens, '__all__') at /opt/dev/projects/szurubooru-client/szurubooru-client/szurubooru_client/tokens.py:23: unsupported node <class 'ast.Call'>
INFO       Finished loading packages
```

</details>

### Expected behavior
I expected that the documentation would build successfully

### Environment information

```bash
griffe --debug-info  # | xclip -selection clipboard
```
- __System__: macOS-14.6-arm64-arm-64bit
- __Python__: cpython 3.12.5 (/Users/slyons/.pyenv/versions/3.12.5/envs/szurubooru-client/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `griffe` v1.1.1

**Comment by pawamoy** [comment]
Hi @slyons, thank you for the report!

What I understand from it is that you're using `__all__ = [..., some_module.__all__, ...]` somewhere, right? Griffe fails to handle this attribute, therefore `__all__` is incomplete and further failures happen down the chain, eventually leading to an alias resolution error (given you commented on a similar issue).

Could you confirm? Or share the relevant bit of code if not?

**Comment by pawamoy** [comment]
Note however that `getattr(_tokens, '__all__')` cannot be supported statically. Since there's no default value, maybe you could simply use `_tokens.__all__` instead?

**Comment by pawamoy** [comment]
I'm not sure to understand how your code works:

```python
from .szurubooru_client import _models

AroundPostResult = _models.AroundPostResult
...
UserResource = _models.UserResource

__doc__ = szurubooru_client.models.__doc__
if hasattr(szurubooru_client.models, "__all__"):
    __all__ = szurubooru_client.models.__all__
```

The module-level `szurubooru_client` name isn't defined here. Doesn't that raise a NameError for you?

**Comment by slyons** [comment]
For `_models` it definitely does (and I've fixed this in the branch). But the solution was to comment out the `__all__` lines and Griffe was happy. 

Sadly, `mkdocstrings` still can't find my modules no matter how hard I try.

**Comment by pawamoy** [comment]
I'll let you know when I release a new version with this change, so you can tell me if it works better.

**Comment by pawamoy** [comment]
v1.2.0 is out, let me know if it works. If not, please open a new issue :slightly_smiling_face:
