### ISSUE TITLE
feature: provide public submodules for different categories of things

### ISSUE THREAD

**Issue by machow** [mkdocstrings/griffe#317]
### Is your feature request related to a problem? Please describe.

Hey, I'm just jumping back into using griffe, and really impressed with all the work that went into the v1 release! This isn't exciting, in that it suggests more moving around objects to the public API, so feel free to punt 😅 .

Currently, `griffe`'s public API is flat, with all classes and functions exposed on the top-level. If you know what you want, this feels quick and easy to get it (via `from griffe import X`). However, it can feel a bit challenging for two things:

* **discovery**: tab completting griffe gives about 200 options, with different categories mixed in terms of order.
* **scoping**: you can specify what you want when importing, but it's often handy to import things like "all 30 docstring models"

### Describe the solution you'd like

Exposed public submodules for different categories of the API. For example, it could mirror the internal API, but only contain public objects...

```python
import griffe.docstrings.models as ds
import griffe.models as dc
```

or some other categorization. I think what's most helpful here is giving a bit of support to discovery and scoping around types of activities.

### Describe alternatives you've considered

People could use the internal `_griffe` package for discovery, and then import explicitly from `griffe`.

**Comment by pawamoy** [comment]
Hey @machow, happy to have you back 😊!

You make good points about discovery and scoping. I sometimes relying on "tab" to see what an object exposes (including private stuff 🙈). 

But I feel like these arguments do not weigh enough in the balance to justify the trouble of having the module layout be part of the API again 😅

- discovery: if you're looking for something in particular, you look at the names (that's what auto completion will give you). You'll quickly notice naming patterns and be able to orient/filter your exploration of the available objects. This gave me an idea for improving the API docs though: to ease this discovery by improving the top level docstring! (`help(griffe)`)
- scoping: you have the ultimate namespace that contains everything already: `griffe` 😀 Seriously, I started doing just `import griffe` and accessing objects from there. It's a quite nice feeling. If you access a lot of objects (and/or a lot of times), you could alias it to `g` or `gr` to make it shorter?

It's not a hard no, but it'll will take a bit more convincing I'm afraid 😄

I'd be especially interested in actual troubles you had using the v1 API, if any 🙂

**Comment by pawamoy** [comment]
You know what, I think there's room for doing something interesting.

I see the benefits of nested namespaces instead of a single global one. But I don't want to deal with deprecations because of objects moving between modules ever again. So maybe we could have namespaces that explicitly declare some members, for both discovery and scoping, but allow to access any object of the API anyway, forever, using `__getattr__`.

Such namespaces would effectively allow better DX without sacrificing maintenance. WDYT? I can come up with a demo in the next days :)

**Comment by machow** [comment]
That's fair -- I definitely think for me it's 90% about static completion suggestions in VS Code and tab-complete in IPython, so some any kind of namespacing contraption seems okay.

It seems like what you're suggesting is sort of similar to pandas or polars accessors, where an attribute on the DataFrame gives access to more methods, e.g.

```python
import pandas as pd
df = pd.DataFrame({"x": ["a", "b"]})

# using str accessor, which hold string related operations
df["x"].str.upper()
```

(only in this case it's on a module, case it sounds like there's a sort of fallback to anything exposed on `griffe`)

**Comment by pawamoy** [comment]
I've ran some experiments, but it's not conclusive. There is no way yet to satisfy both the IDE (VSCode in my case) and Griffe, while avoiding too much repetition or confusion on the long-term. I'll close for now :slightly_smiling_face: Please do elaborate if you think we should really do something about this!

**Comment by pawamoy** [comment]
Just a note that [`SimpleNamespace`](https://docs.python.org/3/library/types.html#types.SimpleNamespace) could be useful here 🤔
