### ISSUE TITLE
Infinite loop with some Google-style docstrings

### ISSUE THREAD

**Issue by WillDaSilva** [mkdocstrings/griffe#41]
**Describe the bug**
When running `mkdocs build ...` on a project I'm working on, it never terminates normally, and instead slowly consumes additional memory while showing no signs of progress being made.

I have not yet been able to determine what in the `.pyx` file is causing this bug to arise, but I will update this issue if/when I do.

Running a [trace](https://docs.python.org/3/library/trace.html) on the Mkdocs build reveals that Griffe gets stuck in a loop in `google.py`:

[trace.log](https://github.com/mkdocstrings/griffe/files/8064963/trace.log)

**To Reproduce**
1. Run `mkdocs build ...` on a project containing whatever sort of Google-style docstrings cause this issue.

**Expected behavior**
The docs should be built, and errors/warnings should be raised as appropriate.

**System:**
- `griffe` version: `0.11.4` (from `mkdocstrings[python]==0.18.0`)
- Python version: 3.10.2
- OS: Linux

**Comment by pawamoy** [comment]
Would it be possible for you to isolate the docstring that makes the parser enter the infinite loop?

**Comment by WillDaSilva** [comment]
Oh excellent, upgrading Griffe fixed the issue. Thanks!
