### ISSUE TITLE
*args and **kwargs lines in Numpydoc parameter sections fail to parse

### ISSUE THREAD

**Issue by FasterSpeeding** [mkdocstrings/griffe#43]
**Describe the bug**
Documentation for *args and **kwargs (as according to https://numpydoc.readthedocs.io/en/latest/format.html#parameters) fails to parse in Numpydoc Parameter and Other Parameter sections

**To Reproduce**
Trying to parse a docstring with the following docstring through numpydocstring
```md
Parameters
------------
*args : typing.Any
    Pass through
**kwargs : typing.Any
    Pass through
```
Leads to the following being logged when using the versions specified below
```
WARNING  -  griffe: alluka\abc.py:461: Could not parse line '*args : typing.Any'
WARNING  -  griffe: alluka\abc.py:461: Could not parse line '**kwargs : typing.Any'
WARNING  -  griffe: alluka\abc.py:461: Empty parameters section at line 4
```
being logged

**Expected behavior**
These lines shouldn't fail to parse

**Screenshots**

**System (please complete the following information):**
griffe == 0.12.5
mkdocstrings-python==0.6.2
py ver 3.10
OS: Win 12 - 1

**Additional context**

**Comment by pawamoy** [comment]
Fixed in version 0.12.6 :slightly_smiling_face:
