### ISSUE TITLE
Examples in Google style do not show

### ISSUE THREAD

**Issue by wxdrizzle** [mkdocstrings/griffe#46]
**Edited**. This issue has been solved by myself. Dear developer, just see my second comment below please, and confirm whether I am correct, or whether there is a better way. Then we can close this issue.

**Describe the bug**
I used the google style to write my python docstrings. The "examples" section is not rendered by mkdocstrings, while other sections such as "Parameters" and "Returns" work well.

**To Reproduce**
Just write a docstring like:

```python
def foo():
    """
    Examples:
        We can print something:
        >>> print('foo')
        'foo'
    """
```

**Expected behavior**
I expect that the "examples" section is rendered, just like the previous python handler's behavior.

**Screenshots**
You can see nothing shown below "Examples".
![image](https://user-images.githubusercontent.com/46703360/154822278-5ec8d4c2-16bb-4393-bc70-2e24cb138f2f.png)

**System (please complete the following information):**
- `griffe` version: 0.12.6
- Python version: 3.9.7
- OS: MacOS 12.2.1

**Additional context**
I tried to debug that. If I change the content in `templates/python/material/_base/docstring/examples.html` from
```html
{{ log.debug() }}
<p><strong>{{ section.title or "Examples:" }}</strong></p>
{% for section_type, sub_section in section.value %}
  {% if section_type == "markdown" %}
    {{ sub_section|convert_markdown(heading_level, html_id) }}
  {% elif section_type == "examples" %}
    {{ sub_section|highlight(language="python", linenums=False) }}
  {% endif %}
{% endfor %}
```
to
```html
{{ log.debug() }}
<p><strong>{{ section.title or "Examples:" }}</strong></p>
{% for section_type, sub_section in section.value %}
    {{ sub_section|highlight(language="python", linenums=False) }}
{% endfor %}
```
Then the section will be rendered but the markdown text is also rendered as code:
![image](https://user-images.githubusercontent.com/46703360/154822571-645da78d-b2b2-4a62-ae83-0156a87e0e3f.png)

Therefore, I think there may be something wrong with `{% if section_type == "markdown" %}` or `{% elif section_type == "examples" %}`, making the value always "False". To confirm this, I add `{{ section_type}}` and `{{ section_type == "examples"}}` to the for loop, and then:
![image](https://user-images.githubusercontent.com/46703360/154822533-0ee583cb-6861-4568-947b-90ac415d9927.png)
You can see that the `section_type` is `DocstringSectionKind.examples`, and `{{ section_type == "examples"}}` is False. I then tried `{{ section_type == "DocstringSectionKind.examples"}}`, but it is still False.

**Comment by wxdrizzle** [comment]
I solved this issue by changing 
```html
{% if section_type == "markdown" %}
```
to
```html
  {% if section_type|string == "DocstringSectionKind.text" %}
```
and also changing 
```html
{% if section_type == "examples" %}
```
to
```html
  {% if section_type|string == "DocstringSectionKind.examples" %}
```
Now it looks like:
![image](https://user-images.githubusercontent.com/46703360/154822866-5e24c907-8bad-4108-b8a9-d8e21ffd1fcc.png)

So for the developer: I think the corresponding code in the template of `examples` need to be modified in such way. Could you please confirm this? 

** How I got that: **
After I found `{{ section_type == "DocstringSectionKind.examples"}}` is still False, I think although the type of `section_type` is indeed `DocstringSectionKind.examples`, but it is not equal to a string "DocstringSectionKind.examples". So I managed to change `section_type` to a string type. So I tried `str(section_type)` but got an error when running mkdocs, from which I got to know that the language (?) is called "jinja2", so I searched "jinja2 how to convert variable to string", and found the answer is `section_type|string`. Finally I came up with the solution.

**Comment by pawamoy** [comment]
Hi again @wxdrizzle! Thanks for the detailed bug report, and the solution to the issue :smile: 
Indeed, I forgot to update this template: we now use enums and can't compare them directly to strings.
And `markdown` was changed to `text`.

So the final fix will look like this:

```html
{% for section_type, sub_section in section.value %}
  {% if section_type.value == "text" %}
    {{ sub_section|convert_markdown(heading_level, html_id) }}
  {% elif section_type.value == "examples" %}
    {{ sub_section|highlight(language="python", linenums=False) }}
  {% endif %}
{% endfor %}
```

Do you want to send a PR with that :slightly_smiling_face:? If not, I'll do it in the afternoon anyway!

**Comment by pawamoy** [comment]
Done! Will release it soon.

**Comment by wxdrizzle** [comment]
Great work! Sorry that I just woke up due to the time difference. Thank you for the quick reply and quick fix @pawamoy 😄

**Comment by pawamoy** [comment]
> Sorry that I just woke up due to the time difference

Haha no problem of course :smile:
