### ISSUE TITLE
Poor documentation of multiple items in Returns docstring

### ISSUE THREAD

**Issue by Bluenix2** [mkdocstrings/griffe#69]
## Summary

I have a project of mine - [`wumpy`](https://github.com/wumpyproject/wumpy) - hosted on Read the Docs (which can be found [here](https://wumpy.readthedocs.io/en/latest/)) built with MKDocs. I am now trying to introduce an API reference using mkdocstrings but Griffe is failing to collect the [`api.interactions`](https://github.com/wumpyproject/docs/blob/main/docs/api/interactions.md) file (note: different repository for the documentation).

## Description

I am using Google-style docstrings in my code and somewhere within the [`wumpy.interactions`](https://github.com/wumpyproject/wumpy/tree/main/library/wumpy-interactions/wumpy/interactions) subpackage Griffe fails to parse the docstring. Below is a subset of the traceback:

```python
  File "C:\Users\%username%\Projects\wumpy-docs\venv\lib\site-packages\griffe\dataclasses.py", line 141, in parsed
    return self.parse()
  File "C:\Users\%username%\Projects\wumpy-docs\venv\lib\site-packages\griffe\dataclasses.py", line 154, in parse
    return parse(self, parser or self.parser, **(options or self.parser_options))
  File "C:\Users\%username%\Projects\wumpy-docs\venv\lib\site-packages\griffe\docstrings\parsers.py", line 51, in parse
    return parsers[parser](docstring, **options)  # type: ignore[operator]
  File "C:\Users\%username%\Projects\wumpy-docs\venv\lib\site-packages\griffe\docstrings\google.py", line 673, in parse
    section, offset = reader(docstring, offset + 1, **options)  # type: ignore[operator]
  File "C:\Users\%username%\Projects\wumpy-docs\venv\lib\site-packages\griffe\docstrings\google.py", line 369, in _read_returns_section
    annotation = annotation.tuple_item(index)
  File "C:\Users\%username%\Projects\wumpy-docs\venv\lib\site-packages\griffe\expressions.py", line 170, in tuple_item
    return self[2][2 * nth]
IndexError: list index out of range
```
> I have uploaded the full traceback [on a gist](https://gist.github.com/Bluenix2/4e5e5108f4022720d0fab616e9ff52c5)

Parsing of `wumpy.rest` also fails that but is a much bigger subpackage and `wumpy.interactions` is built first.

### Unrelated failure

I am aware of a failure in the type annotations which causes the `wumpy-bot` documentation to fail on versions other than Python 3.10. See the [build failure on Read the Docs](https://readthedocs.org/projects/wumpy/builds/16894584/) and this [discussion I opened](https://github.com/python/typing/discussions/1169) about the annotation.

## Installation

I am on a Windows 10 machine running Python 3.10.1 with `griffe==0.19.1` and `mkdocstrings==0.18.1`.

**Comment by Bluenix2** [comment]
I have been able to nail this down to [`_authenticate_request()`](https://github.com/wumpyproject/wumpy/blob/0490eeab470964a9089d274da6d3a7dc28344725/library/wumpy-interactions/wumpy/interactions/app.py#L92) and by looking at Griffe I can see that I was wrong: this is failing to parse the annotation and not the docstring necessarily.

**Comment by pawamoy** [comment]
Hello! Thanks for the report. I believe you just need to indent the continuation lines in your Returns section. Indeed, we chose to support documenting multiple items in Returns, Yields and Receives sections, therefore you need to indent continuation lines for Griffe to properly detect whether you're documenting a single item or multiple ones.

**Comment by Bluenix2** [comment]
To fix this I need to indent the Returns section twice?

**Comment by pawamoy** [comment]
Yes, but only from the second line onward, something like this:

```python
"""
Summary.

Blabla.

Returns:
    Description of what is returned, spanning
        multiple lines. The whole Markdown
        markup is supported, even...

        ...blank lines, as long as indentation
        is consistent.
"""

**Comment by Bluenix2** [comment]
Thinking about it more, is there any way for me to configure this behaviour? I think I rather disable it and place the documentation for each item in the description (which is what I did so far, not knowing about this feature).

It's a cool feature, but I rather indent the Returns section normally than being able to document each item separately for my current project.

**Comment by Bluenix2** [comment]
@valq7711 I think that deserves its own issue judging from the traceback.

**Comment by pawamoy** [comment]
I agree with @Bluenix2, it's another issue :slightly_smiling_face:

**Comment by valq7711** [comment]
sorry guys, i just posted this here to let you know about the issue, not hoping for a fix in the foreseeable future. I would be glad to take part in your project if there were 25 hrs in this day ;)

**Comment by pawamoy** [comment]
That's fine. And I fixed your issue, it's released in 0.19.2 :laughing:

**Comment by valq7711** [comment]
@pawamoy   it's incredible! thanks for your time and great project!!!

**Comment by pawamoy** [comment]
@Bluenix2 I've pushed some docs about Google-style docstrings: https://mkdocstrings.github.io/griffe/docstrings/

**Comment by pawamoy** [comment]
I've improved the docs for the Returns section in particular. There are new options allowing to configure the behavior of the parser. Docs will be published when I release the new version :slightly_smiling_face:
