### ISSUE TITLE
docstrings/sphinx: Support "Examples" sections

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/griffe#7]
**Is your feature request related to a problem? Please describe.**
The goal is to have a common set of features between all parsers.

**Describe the solution you'd like**
The Sphinx parser should be able to parse "Examples" sections, if it makes any sense.

**Comment by pawamoy** [comment]
Closing for cleanup, but if you'd like to work on this, just ask and I'll reopen!

**Comment by griff-rees** [comment]
Hi @pawamoy. The only clear example I've found was last updated in 2014 and isn't part of official documentation and uses `:Example:` singular rather than plural. 

https://thomas-cokelaer.info/tutorials/sphinx/docstring_python.html#template-py-source-file

A relevant snippet:

```python
def function1(self, arg1, arg2, arg3):
    """returns (arg1 / arg2) + arg3

    This is a longer explanation, which may include math with latex syntax
    :math:`\\alpha` (abbridged for ease of example):

    :param arg1: the first value
    :param arg2: the first value
    :param arg3: the first value
    :type arg1: int, float,...
    :type arg2: int, float,...
    :type arg3: int, float,...
    :returns: arg1/arg2 +arg3
    :rtype: int, float

    :Example:

    >>> import template
    >>> a = template.MainClass1()
    >>> a.function1(1,1,1)
    2
    """
    return arg1/arg2 + arg3
```

Note: it renders `>>>` in an on/off way in `html` for ease of copying.

**Comment by griff-rees** [comment]
Two more:

- `:Example:` in a `Sphinx` [`napolean` test](https://github.com/sphinx-doc/sphinx/blob/b0fe7301460cac99755d12a68194b57f0939b13f/tests/test_ext_napoleon_docstring.py#L817)
- `:example:` in a [queirozf](https://queirozf.com) [`post`](https://queirozf.com/entries/python-docstrings-reference-examples#restructuredtext-rest)

**Comment by pawamoy** [comment]
Thanks @griff-rees!

Note that in the Sphinx link, `:Example:` is in a Google style test and is actually used to test that it is *not* recognized and rendered in any useful way: the expected result is the exact same docstring.

I'll leave this issue closed for now, because I don't plan on working on it (and you switched to the Google-style anyway :+1:), but if anyone would like to work on it, just let me know.
