### ISSUE TITLE
Module loading failure

### ISSUE THREAD

**Issue by hlorus** [mkdocstrings/griffe#91]
**Describe the bug**
Mkdocstrings python handler fails when trying to load a [a module](https://github.com/hlorus/CAD_Sketcher).

**To Reproduce**
1. Go to '[Cad Sketcher Repository](https://github.com/hlorus/CAD_Sketcher)'
2. Download repository
cd ~/repos
git clone https://github.com/hlorus/CAD_Sketcher.git
4. Start python interpreter
5. Add the repository path to sys.path
import sys
sys.path.append(r"~/repos")
6. Load the module
import griffe
loader = griffe.loader.GriffeLoader()
loader.load_module("CAD_Sketcher")

**Expected behavior**
load_module should return an object of type griffe.dataclasses.Module and not raise an exception.

**System (please complete the following information):**
- `griffe` version: 0.21.0
- Python version: 3.9
- OS: Windows

[mkdocs_error.txt](https://github.com/mkdocstrings/griffe/files/9001432/mkdocs_error.txt)

**Comment by pawamoy** [comment]
Hello, thanks for the report! Could you try again with version 0.22.0 of Griffe? It should log an error with the location of the problematic annotation. You can then paste your code here so I can see if it should be supported or not.

**Comment by hlorus** [comment]
Sure thing, it spits out the following:

>>> loader.load_module("CAD_Sketcher")
Failed to parse annotation from 'Call' node at CAD_Sketcher/class_defines.py:39
Failed to parse annotation from 'Call' node at CAD_Sketcher/class_defines.py:45
Failed to parse annotation from 'Call' node at CAD_Sketcher/class_defines.py:3393
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:272
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:273
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:371
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:692
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:693
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:3230
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:3358
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:3395
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:3415
Failed to parse annotation from 'Call' node at CAD_Sketcher/operators.py:3517
<Module(PosixPath('/home/yoga/Dropbox/blend/addons/CAD_Sketcher/__init__.py'))>

**Comment by pawamoy** [comment]
Is using callables valid in annotations :thinking: ?

**Comment by hlorus** [comment]
It is apparently. Blender actually kind of missuses annotations to define properties. Here's the official [docs](https://docs.blender.org/api/current/bpy.props.html#operator-example).

**Comment by pawamoy** [comment]
Interesting, thanks. I guess Blender would not work with `from __future__ import annotations` then :thinking:

**Comment by hlorus** [comment]
There was quite some discussion around this however i thought they found some way of supporting it, see:
https://devtalk.blender.org/t/recommended-type-annotations-in-ops/16575

**Comment by hlorus** [comment]
So i tried again building the docs with griffe 0.22 and it seems to properly report the error without aborting. I assume that's the expected behavior so the issue can be closed probably. Thanks alot for your efforts!

**Comment by pawamoy** [comment]
Thank you for coming back and closing with an explanation, that's appreciated :+1:
