### ISSUE TITLE
Module Exports are None

### ISSUE THREAD

**Issue by DarkaMaul** [mkdocstrings/griffe#92]
**Describe the bug**

When using `mkdocstrings-python`, the generation of the documentation fails because of a griffe error.

**To Reproduce**

1. Create the following layout:
```
reproduce/
__init__.py
bar.py
```
2. In `__init__.py`

```python
from reproduce.bar import Foo

__all__ = [
    Foo,
]
```

3. In `bar.py`
```python
class Bar:
    pass
```

4. Run `main.py`:

```python
from griffe.loader import GriffeLoader
loader = GriffeLoader(search_paths=["/tmp/griffe/reproduce/"])
m = loader.load_module("reproduce")
loader.expand_exports(m)
```
5. See error

```console
File ~/.virtualenvs/tmp-156b6e7441e38e4/lib/python3.10/site-packages/griffe/loader.py:210, in GriffeLoader.expand_exports(self, module)
    208     next_module = self.modules_collection[module_path]
    209     self.expand_exports(next_module)
--> 210     expanded |= next_module.exports
    211 else:
    212     expanded.add(export)

TypeError: unsupported operand type(s) for |=: 'set' and 'NoneType'

```

**Expected behavior**

No error. ;)
**System (please complete the following information):**
- `griffe` version: 0.22 (master)
- Python version: 3.9 / 3.10
- OS: Linux

** Potential Fix**

I don't know why but the exports of the module are set as None.
A potential fix is to check that the value is not None before trying to perform the set operation.

```diff
diff --git a/src/griffe/loader.py b/src/griffe/loader.py
index 7095409..8ac6f15 100644
--- a/src/griffe/loader.py
+++ b/src/griffe/loader.py
@@ -207,7 +207,8 @@ class GriffeLoader:
                 module_path = export.full.rsplit(".", 1)[0]  # remove trailing .__all__
                 next_module = self.modules_collection[module_path]
                 self.expand_exports(next_module)
-                expanded |= next_module.exports
+                if next_module.exports is not None:
+                    expanded |= next_module.exports
             else:
                 expanded.add(export)
         module.exports = expanded
```

**Comment by pawamoy** [comment]
Hi, thanks for the report.

The `__all__` variable is supposed to contain strings, not objects directly:

```python
from reproduce.bar import Foo

__all__ = [
    "Foo",
]
```

Could you try this and tell us if the issue still occur?

**Comment by DarkaMaul** [comment]
Yep, the behavior is the same

**Comment by pawamoy** [comment]
Alright, thanks for trying and getting back to me :slightly_smiling_face: 
I'll try to replicate with your example and see how this can be fixed.

**Comment by pawamoy** [comment]
Hello, just tried locally, and the exception is only raised when the item in `__all__` is the object itself and not a string. Using a string instead, which is what is expected, fixes the issue. Could you setup a proper repository with your example above to make sure the issue happens with strings in `__all__` as well? Thanks

**Comment by DarkaMaul** [comment]
Actually, I messed up my experiments indeed using the string fixes the bug.

**Comment by pawamoy** [comment]
Great, thank you for the update :slightly_smiling_face:
