### ISSUE TITLE
IndexError in numpy docstring parser

### ISSUE THREAD

**Issue by krzysztof3-wisniewski** [mkdocstrings/griffe#97]
In `griffe/docstrings/numpy.py` there is a `_read_block()` function, [line 160](https://github.com/mkdocstrings/griffe/blob/master/src/griffe/docstrings/numpy.py#L160-L182) in griffe version 0.22.0.

Condition in [line 175](https://github.com/mkdocstrings/griffe/blob/master/src/griffe/docstrings/numpy.py#L176-L177):
```python
 if is_empty and new_offset < len(lines) + 1 and _is_dash_line(lines[new_offset + 2]):
```
In some cases causes `IndexError: list index out of range`. My guess is that 
```python
new_offset < len(lines) + 1
``` 
could be 
```python
new_offset < len(lines) - 2
```
Proposed change fixes the issue.

**Example docstring**
~~~python
"""Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna
aliqua. Ut enim ad minim veniam, quis nostrud exercitation
ullamco laboris nisi ut aliquip ex ea commodo

Warning: Duis aute irure dolor in reprehenderit!!!

Parameters
----------
ullamco : str
    n ullamco laboris nisi ut aliquip 

Returns
-------
LoremIpsum | Type[LoremIpsum]
    Sed ut perspiciatis unde omnis iste natus error sit voluptatem 
    accusantium doloremque laudantium, totam rem aperiam, ea

Raises
------
LoremIpsum.IpsumLoremIpsum
    Quis autem vel eum iure reprehenderit qui in ea.

Examples
--------
```python
>>> LoremIpsum.from_string("consectetur")
<foofoo: Ipsum.Lorem>
>>> LoremIpsum.from_string("modi/consectetur")
<foofoo: Ipsum.Lorem>
>>> LoremIpsum.from_string("consectetur-7455")
<spam: Ipsum.Lorem::7455>
>>> LoremIpsum.from_string("sdg-dfssd-fsd-sdfdsggds-345677")
<spam: Ipsum.Lorem::345677>

```

"""
~~~

**System:**
- `griffe` version: 0.22.0
- Python version: 3.9
- OS: Windows

**Comment by pawamoy** [comment]
Thank you very much for the detailed report and the example. I'll try to replicate and fix soon :slightly_smiling_face:

**Comment by krzysztof3-wisniewski** [comment]
I should also mention that changing `Examples` to `Example` also hides this problem, for example string I have provided. However, `Examples` title is **not** causing the issue always.

**Comment by pawamoy** [comment]
The difference between `Example` and `Examples` is that `Example` is parsed as an admonition while `Examples` is parsed as a proper section. I had to make this compromise to support both, since they are both common.

I've pushed a fix, your suggested solution was the right one, thanks! Expect a release soon :slightly_smiling_face:
